//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-sample-SSD_SERVICE_ID_sd_hWXCX3NNZeFuNuI5
import { sample as SSD_SERVICE_ID_sd_hWXCX3NNZeFuNuI5 } from './sd-services/sample';

export const UserRoutes = [
    //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-sample-SSD_SERVICE_ID_sd_hWXCX3NNZeFuNuI5
SSD_SERVICE_ID_sd_hWXCX3NNZeFuNuI5,
];
